services:
  mongodb:
    image: mongo:7
    container_name: mongodb_projetoloja
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: loja_produto

    volumes:
      - ./mongo-data:/data/db